name: Build and Push Docker Image to Docker hub
on:
  push:
    branches:
      - main
jobs:
  docker:
    name: Push to Docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        # push image to docker hub     
      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/project-repo:latest

  ec2:
    needs: docker
    name: Push Container to EC2 
    runs-on: ubuntu-latest
    steps:
      - name: Add SSH Key to Access EC2
        run: |
          echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem 
      - name: Deploy Docker image to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        run: |
          ssh -tt -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Pull the latest image from Docker Hub
          docker pull $DOCKER_HUB_USERNAME/project-repo:latest

          # Stop and remove any existing container
          docker stop project-container || true
          docker rm project-container || true

          # Run the new Docker container
          docker run -d --name project-container -p 80:80 $DOCKER_HUB_USERNAME/project-repo:latest
          EOF   
    